# Example Configuration: Regression Task
# Generic template for regression problems

experiment:
  name: "regression-experiment"
  description: "AutoML regression model"

data:
  input_path: "./data/your_data.csv"
  dataset_name: "regression_dataset"
  dataset_description: "Regression training dataset"
  label_column: "target"  # Change to your target column name
  
  columns_to_drop: []
    # - "id"
    # - "record_id"
  
  validation:
    check_missing_values: true
    max_missing_percentage: 50
    check_duplicates: true

feature_engineering:
  enabled: false  # Set to true and configure transformations as needed

compute:
  cluster_name: "cpu-cluster"

automl:
  task: "regression"
  primary_metric: "rmse"
  # Other regression metrics: normalized_root_mean_squared_error, normalized_mean_absolute_error, spearman_correlation
  
  training:
    experiment_timeout_minutes: 60
    iteration_timeout_minutes: 15
    max_concurrent_iterations: 4
    max_cores_per_iteration: -1
    enable_early_stopping: true
    n_cross_validations: 5
  
  featurization:
    mode: "auto"
  
  models:
    allowed: []  # Leave empty to allow all regression models
    blocked: []  # Add model names to exclude specific models
  
  ensemble:
    stack_ensemble_iterations: 5
    ensemble_iterations: 5
  
  onnx:
    enable_onnx_compatible_models: false

output:
  save_preprocessed_data: true
  preprocessed_data_path: "./data/preprocessed"
  
  register_model: true
  model_name: "regression_model"
  model_tags:
    type: "automl"
    framework: "azure-ml"
    task: "regression"
  
  log_level: "INFO"
  log_to_file: true
  log_file_path: "./logs/training.log"
