channels:
- conda-forge
- defaults
dependencies:
- python=3.9
- pip
- pip:
  - azure-ai-ml>=1.11.0
  - azure-identity>=1.12.0
  - scikit-learn>=1.0.0
  - pandas>=1.5.0
  - numpy>=1.23.0
  - mlflow>=2.0.0
  - shap>=0.42.0
  - interpret>=0.4.0
  - raiwidgets>=0.25.0
  - responsibleai>=0.25.0
name: rai_model_env
