channels:
- conda-forge
dependencies:
- python=3.12.7
- pip<=24.2
- pip:
  - mlflow==3.7.0
  - numpy==2.3.3
  - pandas==2.3.3
  - psutil==7.1.0
  - pyarrow==22.0.0
  - scikit-learn==1.7.2
  - scipy==1.16.3
name: mlflow-env
